# tasks file for neovim-conf
- name: mkdir $XDG_CONFIG_HOME
  file:
    path: "{{neovim_conf_xdg_config_home}}"
    state: directory
- name: mkdir repo's parent directory
  file:
    path: "{{neovim_conf_cloned_dest|dirname}}"
    state: directory
- name: Clone the vim config repository
  git:
    repo: "{{neovim_conf_repo}}"
    dest: "{{neovim_conf_cloned_dest}}"
    version: "{{neovim_conf_version}}"
- name: make symbolic link
  file:
    src: "{{neovim_conf_cloned_dest}}"
    dest: "{{neovim_conf_xdg_config_home}}/nvim"
    state: link
  when: neovim_conf_cloned_dest != "{}/nvim".format(neovim_conf_xdg_config_home)
- name: mkdir undodir
  file:
    path: "{{neovim_conf_undodir}}"
    state: directory
  when: neovim_conf_undodir is defined
